/**
 * UniGear Database Type Definitions. UniGear 数据库类型定义
 *
 * Auto-generated from the database schema. 根据数据库 schema 生成
 * This is the SINGLE SOURCE OF TRUTH for all frontend types.
 * 这是所有前端类型的唯一事实来源
 *
 * Contract-Driven: Both app-web and app-mobile import from this file.
 * 合约驱动：Web 端和移动端均从此文件导入类型
 */

// ============================================================
// Enum Types. 枚举类型
// ============================================================

/** User role. 用户角色 */
export type UserRole = 'student' | 'admin' | 'staff';

/** Asset physical condition. 资产物理状况 */
export type AssetCondition = 'new' | 'good' | 'fair' | 'poor' | 'damaged';

/** Asset availability status. 资产可用状态 */
export type AssetStatus = 'available' | 'borrowed' | 'maintenance' | 'retired';

/** Warranty status. 保修状态 */
export type WarrantyStatus = 'active' | 'expired' | 'none';

/** Booking lifecycle status. 借用生命周期状态 */
export type BookingStatus =
    | 'pending'
    | 'approved'
    | 'rejected'
    | 'active'
    | 'lost_reported'
    | 'lost'
    | 'returned'
    | 'overdue'
    | 'cancelled'
    | 'suspended';

/** Damage severity level. 损坏严重程度 */
export type DamageSeverity = 'minor' | 'moderate' | 'severe' | 'lost';

/** Damage report status. 损坏报告状态 */
export type DamageReportStatus = 'open' | 'investigating' | 'resolved' | 'dismissed';

/** Compensation case status. 赔偿主状态 */
export type CompensationStatus =
    | 'under_review'
    | 'awaiting_signature'
    | 'awaiting_payment'
    | 'partially_paid'
    | 'paid'
    | 'waived';

/** Compensation record type. 赔偿记录类型 */
export type CompensationRecordType =
    | 'assessment'
    | 'status_update'
    | 'signature'
    | 'payment'
    | 'adjustment'
    | 'note';

/** Notification type. 通知类型 */
export type NotificationType =
    | 'booking_approved'
    | 'booking_rejected'
    | 'booking_pending'    // 学生提交预约，等待管理员审批
    | 'booking_suspended'
    | 'booking_restored'
    | 'booking_cancelled'
    | 'return_submitted'   // 学生提交归还，等待管理员验证
    | 'return_reminder'
    | 'overdue_alert'
    | 'damage_reported'
    | 'compensation_update'
    | 'review_reply'
    | 'system';

// ============================================================
// Table Row Types. 表行类型
// ============================================================

/** Profile row — extends auth.users. 用户资料行 */
export interface Profile {
    id: string;
    full_name: string;
    student_id: string | null;
    email: string;
    phone: string;
    avatar_url: string;
    role: UserRole;
    credit_score: number;
    department: string;
    created_at: string;
    updated_at: string;
}

/** Category row. 分类行 */
export interface Category {
    id: string;
    name: string;
    name_zh: string;
    icon: string;
    description: string;
    created_at: string;
}

/** Asset row. 资产行 */
export interface Asset {
    id: string;
    category_id: string;
    created_by: string | null;
    name: string;
    description: string;
    serial_number: string | null;
    qr_code: string | null;
    condition: AssetCondition;
    status: AssetStatus;
    location: string;
    images: string[];
    is_archived: boolean;
    warranty_status: WarrantyStatus;
    warranty_expiry: string | null;
    purchase_date: string | null;
    purchase_price: number | null;
    created_at: string;
    updated_at: string;
}

/** Booking row. 借用记录行 */
export interface Booking {
    id: string;
    asset_id: string;
    borrower_id: string;
    approver_id: string | null;
    status: BookingStatus;
    start_date: string;
    end_date: string;
    actual_return_date: string | null;
    pickup_photo_url: string;
    return_photo_url: string;
    notes: string;
    rejection_reason: string;
    created_at: string;
    updated_at: string;
}

/** Damage report row. 损坏报告行 */
export interface DamageReport {
    id: string;
    booking_id: string;
    asset_id: string;
    reporter_id: string;
    description: string;
    severity: DamageSeverity;
    photo_urls: string[];
    status: DamageReportStatus;
    resolution_notes: string;
    /** Whether this report was auto-generated by the 30-day overdue system. 是否由30天逾期系统自动生成 */
    auto_generated: boolean;
    created_at: string;
    updated_at: string;
}

/** Notification row. 通知行 */
export interface Notification {
    id: string;
    user_id: string;
    type: NotificationType;
    title: string;
    message: string;
    is_read: boolean;
    metadata: Record<string, unknown>;
    created_at: string;
}

/**
 * Credit score change log row. 信用分变动日志行
 *
 * One record per credit score change (deduction or bonus).
 * 每次信用分变动（扣分或加分）对应一条记录。
 */
export interface CreditScoreLog {
    id: string;
    user_id: string;
    /** Change amount: negative = deduction, positive = bonus. 变化量：负数扣分，正数加分 */
    delta: number;
    /** Credit score balance after this change. 本次变动后的信用分余额 */
    balance_after: number;
    /**
     * Reason code, maps to i18n key in creditScoreLog.reasons.
     * 原因代码，对应 i18n key。
     * Known values: overdue_booking, overdue_day1, overdue_day7, overdue_day30_lost, return_bonus,
     * damage_minor, damage_moderate, damage_severe, admin_manual
     */
    reason: string;
    /** Associated booking ID, null for system operations. 关联借用单 ID，系统操作时为 null */
    booking_id: string | null;
    created_at: string;
}

/** Compensation case row. 赔偿主档 */
export interface CompensationCase {
    id: string;
    damage_report_id: string;
    booking_id: string;
    asset_id: string;
    liable_user_id: string;
    status: CompensationStatus;
    assessed_amount: number | null;
    agreed_amount: number | null;
    paid_amount: number;
    currency: string;
    payment_reference: string;
    due_date: string | null;
    contact_person: string;
    contact_email: string;
    contact_phone: string;
    contact_office: string;
    office_hours: string;
    admin_notes: string;
    created_at: string;
    updated_at: string;
}

/** Compensation record row. 赔偿明细记录 */
export interface CompensationRecord {
    id: string;
    compensation_case_id: string;
    record_type: CompensationRecordType;
    title: string;
    description: string;
    amount: number | null;
    payment_method: string;
    reference_no: string;
    created_by: string | null;
    created_at: string;
}

/** Review row. 评价行 */
export interface Review {
    id: string;
    booking_id: string;
    reviewer_id: string;
    rating: number;
    comment: string;
    created_at: string;
}

/** Review reply row. 评价回复行 */
export interface ReviewReply {
    id: string;
    review_id: string;
    author_id: string;
    content: string;
    created_at: string;
}

/** Audit log row. 审计日志行 */
export interface AuditLog {
    id: string;
    created_at: string;
    operator_id: string | null;
    operator_name: string | null;
    operation_type: string;
    resource_type: string;
    resource_id: string | null;
    resource_name: string | null;
    change_description: string;
    metadata: Record<string, unknown>;
}

// ============================================================
// Insert Types (omit auto-generated fields). 插入类型
// ============================================================

export type ProfileInsert = Omit<Profile, 'created_at' | 'updated_at'>;
export type CategoryInsert = Omit<Category, 'id' | 'created_at'>;
export type AssetInsert = Omit<Asset, 'id' | 'created_at' | 'updated_at'>;
export type BookingInsert = Omit<Booking, 'id' | 'created_at' | 'updated_at' | 'approver_id' | 'actual_return_date'>;
export type DamageReportInsert = Omit<DamageReport, 'id' | 'created_at' | 'updated_at' | 'status' | 'resolution_notes'>;
export type NotificationInsert = Omit<Notification, 'id' | 'created_at' | 'is_read'>;
export type CreditScoreLogInsert = Omit<CreditScoreLog, 'id' | 'created_at'>;
export type CompensationCaseInsert = Omit<CompensationCase, 'id' | 'created_at' | 'updated_at'>;
export type CompensationRecordInsert = Omit<CompensationRecord, 'id' | 'created_at'>;
export type ReviewInsert = Omit<Review, 'id' | 'created_at'>;
export type ReviewReplyInsert = Omit<ReviewReply, 'id' | 'created_at'>;
export type AuditLogInsert = Omit<AuditLog, 'id' | 'created_at'>;

// ============================================================
// Update Types (all fields optional). 更新类型
// ============================================================

export type ProfileUpdate = Partial<Omit<Profile, 'id' | 'created_at' | 'updated_at'>>;
export type CategoryUpdate = Partial<Omit<Category, 'id' | 'created_at'>>;
export type AssetUpdate = Partial<Omit<Asset, 'id' | 'created_at' | 'updated_at'>>;
export type BookingUpdate = Partial<Omit<Booking, 'id' | 'created_at' | 'updated_at'>>;
export type DamageReportUpdate = Partial<Omit<DamageReport, 'id' | 'created_at' | 'updated_at'>>;
export type NotificationUpdate = Partial<Pick<Notification, 'is_read'>>;
export type CompensationCaseUpdate = Partial<Omit<CompensationCase, 'id' | 'created_at' | 'updated_at'>>;
export type ReviewUpdate = Partial<Pick<Review, 'rating' | 'comment'>>;

// ============================================================
// Supabase Database Interface. Supabase 数据库接口
// ============================================================

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: Profile;
                Insert: ProfileInsert;
                Update: ProfileUpdate;
                Relationships: [];
            };
            categories: {
                Row: Category;
                Insert: CategoryInsert;
                Update: CategoryUpdate;
                Relationships: [];
            };
            assets: {
                Row: Asset;
                Insert: AssetInsert;
                Update: AssetUpdate;
                Relationships: [];
            };
            bookings: {
                Row: Booking;
                Insert: BookingInsert;
                Update: BookingUpdate;
                Relationships: [];
            };
            damage_reports: {
                Row: DamageReport;
                Insert: DamageReportInsert;
                Update: DamageReportUpdate;
                Relationships: [];
            };
            notifications: {
                Row: Notification;
                Insert: NotificationInsert;
                Update: NotificationUpdate;
                Relationships: [];
            };
            credit_score_logs: {
                Row: CreditScoreLog;
                Insert: CreditScoreLogInsert;
                Update: never;
                Relationships: [];
            };
            compensation_cases: {
                Row: CompensationCase;
                Insert: CompensationCaseInsert;
                Update: CompensationCaseUpdate;
                Relationships: [];
            };
            compensation_records: {
                Row: CompensationRecord;
                Insert: CompensationRecordInsert;
                Update: never;
                Relationships: [];
            };
            reviews: {
                Row: Review;
                Insert: ReviewInsert;
                Update: ReviewUpdate;
                Relationships: [];
            };
            review_replies: {
                Row: ReviewReply;
                Insert: ReviewReplyInsert;
                Update: never;
                Relationships: [];
            };
            audit_logs: {
                Row: AuditLog;
                Insert: AuditLogInsert;
                Update: never;
                Relationships: [];
            };
        };
        Views: {};
        Functions: {
            activate_booking: {
                Args: { p_booking_id: string };
                Returns: void;
            };
            return_booking: {
                Args: { p_booking_id: string; p_photo_url: string };
                Returns: void;
            };
            check_overdue_bookings: {
                Args: Record<string, never>;
                Returns: void;
            };
            check_suspended_maintenance_bookings: {
                Args: Record<string, never>;
                Returns: void;
            };
            update_credit_score: {
                Args: { p_user_id: string; p_delta: number; p_reason: string };
                Returns: void;
            };
            create_booking: {
                Args: { p_asset_id: string; p_start_date: string; p_end_date: string; p_notes: string };
                Returns: string;
            };
        };
        Enums: {
            user_role: UserRole;
            asset_condition: AssetCondition;
            asset_status: AssetStatus;
            warranty_status: WarrantyStatus;
            booking_status: BookingStatus;
            damage_severity: DamageSeverity;
            damage_report_status: DamageReportStatus;
            compensation_status: CompensationStatus;
            compensation_record_type: CompensationRecordType;
            notification_type: NotificationType;
        };
        CompositeTypes: {};
    };
}
