export type CompensationStatus =
  | 'under_review'
  | 'awaiting_signature'
  | 'awaiting_payment'
  | 'partially_paid'
  | 'paid'
  | 'waived';

export interface EstimateCompensationInput {
  purchasePrice: number | null;
  purchaseDate: string | null;
  severity: string;
  reportStatus?: string | null;
  autoGenerated?: boolean | null;
  reporterId?: string | null;
  borrowerId?: string | null;
}

export const DAMAGE_COEFFICIENT: Record<string, number> = {
  minor: 0.2,
  moderate: 0.5,
  severe: 1.0,
  lost: 1.0,
};

export const DEFAULT_COMPENSATION_CONTACT = {
  person: 'Campus Asset Service Desk',
  email: 'assets-office@unigear.edu',
  phone: '+358 40 123 4567',
  office: 'A102 Asset Service Office',
  officeHours: 'Mon-Fri 09:00-16:00',
};

export function getDepreciationRatio(purchaseDate: string | null): number {
  if (!purchaseDate) return 0.5;

  const years = (Date.now() - new Date(purchaseDate).getTime()) / (1000 * 60 * 60 * 24 * 365.25);

  if (years <= 1) return 1.0;
  if (years <= 3) return 0.8;
  if (years <= 5) return 0.5;
  return 0.2;
}

export function estimateCompensationAmount({
  purchasePrice,
  purchaseDate,
  severity,
  reportStatus,
  autoGenerated,
  reporterId,
  borrowerId,
}: EstimateCompensationInput): number | null {
  if (reportStatus === 'dismissed') return 0;
  if (purchasePrice == null) return null;

  const depreciation = getDepreciationRatio(purchaseDate);

  if (severity === 'lost') {
    const isUserSelfReport = !autoGenerated && reporterId && borrowerId && reporterId === borrowerId;
    if (isUserSelfReport) {
      return Math.round(purchasePrice * depreciation);
    }
    return Math.round(purchasePrice);
  }

  const coefficient = DAMAGE_COEFFICIENT[severity] ?? 0.5;
  return Math.round(purchasePrice * depreciation * coefficient);
}

export function getSuggestedCompensationStatus(
  reportStatus: string,
  agreedAmount: number | null,
  paidAmount: number
): CompensationStatus {
  if (reportStatus === 'dismissed') return 'waived';

  const targetAmount = agreedAmount ?? 0;
  if (targetAmount <= 0 && reportStatus === 'resolved') return 'waived';
  if (paidAmount >= targetAmount && targetAmount > 0) return 'paid';
  if (paidAmount > 0) return 'partially_paid';
  if (reportStatus === 'resolved') return 'awaiting_signature';
  return 'under_review';
}

export function getOutstandingAmount(
  agreedAmount: number | null,
  assessedAmount: number | null,
  paidAmount: number
): number {
  const target = agreedAmount ?? assessedAmount ?? 0;
  return Math.max(0, target - paidAmount);
}

export function buildCompensationReference(sourceId: string): string {
  const compact = sourceId.replace(/-/g, '').toUpperCase().slice(0, 8);
  return `CMP-${compact}`;
}
